# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Argon Eon Support
version: "1.1.9"
slug: argon-eon
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
init: false
gpio: true
#full_access: true
uart: true
devices:
  - /dev/i2c-1
apparmor: false
hassio_api: true
# image: "ghcr.io/home-assistant/{arch}-addon-example"
