# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Argon Eon Support
version: "1.1.1"
slug: argon-eon
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
init: false
gpio: true
devicetree: true
hassio_api: true
options:
  message: "FIXME Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
