name: Argon Eon Support
version: "1.1.15"
slug: argon-eon
description: Argon Eon fan and oled controller
url: "https://github.com/tbaumann/homeassistant-addons/tree/main/argon-eon"
arch:
  - aarch64
startup: services
init: false
gpio: true
uart: true
devices:
  - /dev/i2c-1
apparmor: false
devicetree: true
